dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: nEjluyUiEuuQsyO7d23KIXtjDWvcIl24jrzWiPTY3WZbh0yBEp0CfY9IDR4a5LMCPMoLmalpPswqGCglsy7Wz4t+nAoS356IF83lanjMWSIpNrLoLhWvgxhdGDxzITB5fPuOnFmwinvPM69QqysI2VlY+EC5fkDMA2HuCzxpnn5wrRLrja005gULAuEMl8R2WdKnj0jqxUUhLDdoslSnkijpi5opuSU4LNMOEKrga3GcPbr/xBX3CeTOV4XZ6kp/bnBMHb3Pe+US+E/Ytwkoj/+8zBUq8lyyeJkReAujsHg5vSd6KrTnJMRw4qPND05cCH61nlfRFvsp5hzPiH2MfJuwNOfyV3WI0ytKeNWcYBysDtBuGuqEtV0OhB9C3QREAML1jk2liE+G8TBtuGuMCgUchJZGFwzejTGsZfhZ6rmh0v5kgnEXjwKZw2lXY4PB9xYXSV/xm5QwbEZ2R2jCnc5/mHAgWx3xGimTI9RsYO5xtRexXLpoaKmMXUI7b4w4VkpmiOyTnjyVvGvlo+30V0yHCTiv93GvvhwCyAPNUCRAdaORQRrrj6tqV4WCtXVH6TDhrPkd+i60E1s4tRwSZ7wljI79RKcwnnvVShZoxMl31QAyUSIvTO4xCvkZNd0ZDQPj7SL4a8WX9vb1wguM1RArz4jcAGVuRsC0B324FDw=
